import { readFileSync } from 'node:fs';
import {
  FontResolutionError,
  createFontResourceSnapshot,
  harfBuzzFontValidator,
  sha256FontBytes,
  type FontRequest,
} from '../../index.ts';
import { createHarfBuzzParityValue } from './harfbuzz-parity-fixture.ts';

const request: FontRequest = { family: 'DejaVu Sans', weight: 400, style: 'normal' };
const bytes = new Uint8Array(readFileSync(new URL('./fonts/DejaVuSans.ttf', import.meta.url)));
const snapshot = createFontResourceSnapshot({
  epoch: 1,
  maxFontBytes: 2_000_000,
  resources: [
    {
      request,
      id: 'dejavu-sans-regular',
      bytes,
      hash: sha256FontBytes(bytes),
      faceIndex: 0,
    },
  ],
  validateFont: harfBuzzFontValidator,
});
const font = snapshot.resolve(request);
if (font instanceof FontResolutionError) throw font;

const goldenJson = JSON.stringify(createHarfBuzzParityValue(font));
process.stdout.write(
  `// Generated by generate-harfbuzz-parity-golden.ts under Bun server runtime.\n` +
    `export const HARFBUZZ_PARITY_GOLDEN_JSON = ${JSON.stringify(goldenJson)};\n`
);
