// One-off: parse packages/react/src/components/ui/Icons.tsx and emit
// packages/vue/src/components/ui/icon-paths.json — a `name → string[]`
// map of SVG `d` attributes that the Vue Icons.vue component consumes.
//
// Run with: bun scripts/extract-icons.mjs
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const SRC = resolve(ROOT, 'packages/react/src/components/ui/Icons.tsx');
const OUT = resolve(ROOT, 'packages/vue/src/components/ui/icon-paths.json');

const src = readFileSync(SRC, 'utf8');

// Match each `export function IconFoo(props: IconProps) { return (<SvgIcon ...>BODY</SvgIcon>...`
const fnRe = /export function (Icon\w+)\(props: IconProps\)\s*\{\s*return\s*\(\s*<SvgIcon[^>]*>([\s\S]*?)<\/SvgIcon>/g;
const fnPaths = {};
for (const m of src.matchAll(fnRe)) {
  const [, fn, body] = m;
  const paths = [];
  for (const pm of body.matchAll(/<path d="([^"]+)"\s*\/>/g)) paths.push(pm[1]);
  if (paths.length) fnPaths[fn] = paths;
}

// Build kebab-name → fn mapping from the `iconMap` literal.
const block = src.match(/const iconMap[^=]*=\s*\{([\s\S]*?)\n\};/);
const out = {};
if (block) {
  for (const m of block[1].matchAll(/^\s*([\w-]+|'[^']+')\s*:\s*(Icon\w+)/gm)) {
    let key = m[1];
    if (key.startsWith("'")) key = key.slice(1, -1);
    if (fnPaths[m[2]]) out[key] = fnPaths[m[2]];
  }
}

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, JSON.stringify(out, null, 2));

// Also emit a TypeScript module into the SHARED package.
//
// `engine-editor` owns the chrome descriptor and must name an icon per control, but it
// cannot import `packages/vue` — that inverts the enforced dependency DAG. Emitting the
// same generated data from the same extractor keeps ONE source of truth without a
// cross-package import, and a `.ts` module avoids needing `resolveJsonModule` in every
// consuming project.
const SHARED_OUT = resolve(ROOT, 'packages/core/src/editor/generated-icon-paths.ts');
const banner = [
  '// GENERATED by scripts/extract-icons.mjs from',
  '// packages/react/src/components/ui/Icons.tsx. Do not edit by hand: hand-authored path',
  '// data is what this file exists to eliminate. Re-run the script after changing an icon.',
  '',
  '/** Material Symbol name → SVG path data (viewBox "0 -960 960 960"). */',
  'export const GENERATED_ICON_PATHS: Readonly<Record<string, readonly string[]>> = ',
].join('\n');
writeFileSync(SHARED_OUT, `${banner}${JSON.stringify(out, null, 2)} as const;\n`);

console.log(`extracted ${Object.keys(fnPaths).length} icons, mapped ${Object.keys(out).length} names → ${OUT}`);
console.log(`shared module → ${SHARED_OUT}`);
