// Paragraph acceptance through the private harness (tasks 8.2, 8.3).
//
// One document, one gate, the whole slice: load a fixture covering known AND unknown ordered
// OOXML plus every accepted D8 property, edit and format it through the paginated surface,
// check semantic caret and selection, save, and verify BOTH D9 oracles against a reopen.
//
// Fixture: `e2e/fixtures/paragraph-acceptance.docx`, regenerated by
// `node scripts/make-acceptance-fixture.mjs`.

import { GlobalRegistrator } from '@happy-dom/global-registrator';
if (!GlobalRegistrator.isRegistered) GlobalRegistrator.register();

import { describe, expect, test } from 'bun:test';
import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  ACCEPTED_PARAGRAPH_PROPERTIES,
  ACCEPTED_RUN_PROPERTIES,
  canonicalOoxmlFingerprint,
  diffSemanticDigests,
  readOoxmlPackage,
  semanticDigest,
} from '@docx-editor.dev/core/store';
import { caretAt, fragmentsOfParagraph, linesOf } from '@docx-editor.dev/core/layout';
import { mountPaginatedSurface, type PaginatedSurface } from '../paginated-surface.ts';

const FIXTURE = join(
  dirname(fileURLToPath(import.meta.url)),
  '../../../../../e2e/fixtures/paragraph-acceptance.docx'
);

function bytes(): Uint8Array {
  return new Uint8Array(readFileSync(FIXTURE));
}

/**
 * Put the caret at a model position in the first paragraph.
 *
 * Addresses the MODEL, not the screen. Positioning by coordinates went through the surface's
 * own hit test, which no production path uses any more — the browser resolves pointer
 * positions over the painted text. `hitTestSemantic` keeps its own tests in `engine-layout`,
 * where the page-relative contract that makes it tricky actually lives.
 */
function putCaret(surface: PaginatedSurface, offset: number, paragraphIndex = 0): void {
  const paragraphId = surface.session.paragraphIds()[paragraphIndex]!;
  surface.setSelection({
    anchor: { paragraphId, offset },
    head: { paragraphId, offset },
  });
}

function mount(source: Uint8Array = bytes()): PaginatedSurface {
  const result = mountPaginatedSurface(document.createElement('div'), source, { scale: 1 });
  if (!result.ok) throw new Error(`${result.reason}: ${result.detail ?? ''}`);
  return result.surface;
}

/** Every property element name present anywhere in a part, for coverage assertions. */
function propertyNames(source: Uint8Array): Set<string> {
  const read = readOoxmlPackage(source);
  if (!read.ok) throw new Error(read.reason);
  const names = new Set<string>();
  const walk = (node: {
    kind: string;
    localName?: string;
    children?: readonly unknown[];
  }): void => {
    if (node.kind === 'textValue') return;
    if (node.kind === 'runProperties' || node.kind === 'paragraphProperties') {
      for (const child of (node.children ?? []) as { localName?: string }[]) {
        if (child.localName) names.add(child.localName);
      }
    }
    for (const child of (node.children ?? []) as never[]) walk(child);
  };
  walk(read.package.parts.get(read.package.mainDocumentPart)!.root as never);
  return names;
}

describe('the acceptance fixture covers the declared boundary (task 8.2)', () => {
  test('it carries every accepted RUN property', () => {
    const present = propertyNames(bytes());
    const missing = ACCEPTED_RUN_PROPERTIES.filter((name) => !present.has(name));
    expect(missing).toEqual([]);
  });

  test('it carries every accepted PARAGRAPH property', () => {
    const present = propertyNames(bytes());
    const missing = ACCEPTED_PARAGRAPH_PROPERTIES.filter((name) => !present.has(name));
    expect(missing).toEqual([]);
  });

  test('it carries unknown ordered OOXML in every position it can occupy', () => {
    const surface = mount();
    const xml = JSON.stringify(surface.session.part());
    // Inside a run, nested in a known rPr, and as a direct paragraph child.
    expect(xml).toContain('urn:test:clip');
    expect(xml).toContain('futureRunProp');
    expect(xml).toContain('futureParagraphChild');
  });

  test('it carries authored whitespace, a tab and a hard break', () => {
    const body = mount().session.bodyText();
    expect(body).toContain('  leading and trailing spaces  ');
    expect(body).toContain('\t');
    expect(body).toContain('\n');
  });

  test('it produces a paragraph that crosses a page boundary', () => {
    const surface = mount();
    const crossing = surface.session
      .paragraphIds()
      .map((id) => fragmentsOfParagraph(surface.layout(), id))
      .filter((fragments) => fragments.length > 1);
    expect(crossing.length).toBeGreaterThan(0);
    // Fragments of one paragraph are contiguous and consecutively indexed.
    for (const fragments of crossing) {
      for (let index = 1; index < fragments.length; index += 1) {
        expect(fragments[index]!.fragmentIndex).toBe(fragments[index - 1]!.fragmentIndex + 1);
        expect(fragments[index]!.range.start).toBe(fragments[index - 1]!.range.end);
      }
    }
  });
});

describe('load, edit, format, save and reopen (task 8.3)', () => {
  test('the document loads and paginates', () => {
    const surface = mount();
    expect(surface.session.editable).toBe(true);
    expect(surface.state().pageCount).toBeGreaterThan(1);
    expect(linesOf(surface.layout()).length).toBeGreaterThan(10);
  });

  test('an edit commits and survives save and reopen', () => {
    const surface = mount();
    const first = surface.session.paragraphIds()[0]!;
    putCaret(surface, 0);
    expect(surface.state().selection.head.paragraphId).toBe(first);
    surface.type('EDITED ');
    expect(surface.session.bodyText()).toContain('EDITED ');

    const reopened = mount(surface.session.save());
    expect(reopened.session.bodyText()).toContain('EDITED ');
  });

  test('formatting applies to exactly the requested range', () => {
    const surface = mount();
    const first = surface.session.paragraphIds()[0]!;
    const result = surface.session.applyTreeOps([
      {
        op: 'setRunProperties',
        paragraphId: first,
        start: 0,
        end: 4,
        properties: [{ localName: 'b' }],
      },
    ]);
    expect(result.committed).toBe(true);
    const reopened = mount(surface.session.save());
    const spans = linesOf(reopened.layout())
      .filter((line) => line.range.paragraphId === reopened.session.paragraphIds()[0])
      .flatMap((line) => line.spans);
    const bolded = spans.filter((span) => span.style.bold);
    expect(bolded.length).toBeGreaterThan(0);
    expect(bolded.every((span) => span.range.start < 4)).toBe(true);
  });

  test('semantic caret and selection answer from the layout records', () => {
    const surface = mount();
    putCaret(surface, 0);
    surface.navigate('right');
    surface.navigate('right');
    expect(surface.state().selection.head.offset).toBe(2);
    surface.navigate('lineEnd', true);
    const selection = surface.state().selection;
    expect(selection.head.offset).toBeGreaterThan(selection.anchor.offset);
  });

  test('BOTH D9 oracles pass across save and reopen', () => {
    const surface = mount();
    const first = surface.session.paragraphIds()[0]!;
    surface.session.applyTreeOps([{ op: 'insertText', paragraphId: first, offset: 0, text: 'X' }]);

    const saved = surface.session.save();
    const before = surface.session.part();
    const reopened = readOoxmlPackage(saved);
    if (!reopened.ok) throw new Error(reopened.reason);
    const after = reopened.package.parts.get(reopened.package.mainDocumentPart)!;

    // Oracle 1: the namespace-aware canonical tree fingerprint.
    expect(canonicalOoxmlFingerprint(after)).toBe(canonicalOoxmlFingerprint(before));
    // Oracle 2: the reopened semantic digest. Neither may cover for the other.
    expect(diffSemanticDigests(semanticDigest([before]), semanticDigest([after]))).toEqual([]);
  });

  test('unknown content survives an edit, a save and a reopen unchanged', () => {
    const surface = mount();
    const first = surface.session.paragraphIds()[0]!;
    surface.session.applyTreeOps([
      { op: 'insertText', paragraphId: first, offset: 0, text: 'edit ' },
    ]);
    const reopened = mount(surface.session.save());
    const xml = JSON.stringify(reopened.session.part());
    expect(xml).toContain('urn:test:clip');
    expect(xml).toContain('futureRunProp');
    expect(xml).toContain('futureParagraphChild');
    expect(xml).toContain('keep-me');
  });

  test('authored whitespace is preserved verbatim through the round trip', () => {
    const surface = mount();
    const reopened = mount(surface.session.save());
    expect(reopened.session.bodyText()).toContain('  leading and trailing spaces  ');
  });

  test('an unedited document round-trips with no semantic change at all', () => {
    const surface = mount();
    const before = surface.session.part();
    const reopened = readOoxmlPackage(surface.session.save());
    if (!reopened.ok) throw new Error(reopened.reason);
    const after = reopened.package.parts.get(reopened.package.mainDocumentPart)!;
    expect(diffSemanticDigests(semanticDigest([before]), semanticDigest([after]))).toEqual([]);
    expect(canonicalOoxmlFingerprint(after)).toBe(canonicalOoxmlFingerprint(before));
  });

  test('every paragraph carries a valid unique w14:paraId, preserved across save/reopen', () => {
    // The fixture has none authored — every id here is minted at open. The oracles above
    // still pass because a reopen reads back exactly what the session serialized.
    const surface = mount();
    const ids = surface.session
      .paragraphIds()
      .map((paragraphId) => surface.session.paraIdOf(paragraphId));
    expect(ids.length).toBeGreaterThan(0);
    for (const id of ids) expect(id).toMatch(/^[0-9A-F]{8}$/);
    expect(new Set(ids).size).toBe(ids.length);
    const reopened = mount(surface.session.save());
    expect(
      reopened.session.paragraphIds().map((paragraphId) => reopened.session.paraIdOf(paragraphId))
    ).toEqual(ids);
  });

  test('every accepted property survives the round trip', () => {
    const surface = mount();
    const present = propertyNames(surface.session.save());
    for (const name of ACCEPTED_RUN_PROPERTIES) expect(present.has(name)).toBe(true);
    for (const name of ACCEPTED_PARAGRAPH_PROPERTIES) expect(present.has(name)).toBe(true);
  });

  test('undo and redo walk the canonical store after painted editing', () => {
    const surface = mount();
    const original = surface.session.bodyText();
    putCaret(surface, 0);
    surface.type('Z');
    expect(surface.session.bodyText()).not.toBe(original);
    surface.session.undo();
    expect(surface.session.bodyText()).toBe(original);
    surface.session.redo();
    expect(surface.session.bodyText()).not.toBe(original);
  });
});
